import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faCheck,
  faMinus,
  faTimes,
  faSpinner,
  faTrash,
  faEye,
  faEyeSlash,
  faArrowLeft,
  faArrowRight,
  faChevronRight,
  faChevronLeft,
  faCaretRight,
  faAngleDown,
  faAngleRight,
  faSortUp,
  faSortDown,
  faCircle,
} from "@fortawesome/free-solid-svg-icons";

library.add(
  faCheck,
  faMinus,
  faTimes,
  faSpinner,
  faTrash,
  faEye,
  faEyeSlash,
  faArrowLeft,
  faArrowRight,
  faChevronRight,
  faChevronLeft,
  faCaretRight,
  faAngleDown,
  faAngleRight,
  faSortUp,
  faSortDown,
  faCircle
);
